# Generated by Django 6.0.3 on 2026-05-24 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("COD", "CASH ON DELIVERY"), ("CARD", "CARD/ONLINE PAYMENT")],
                default="cod",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("paid", "paid"),
                    ("failed", "failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
