# Generated by Django 6.0.3 on 2026-05-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_payment_method_order_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="full_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("COD", "cash on deliverey"), ("CARD", "card/online payment")],
                default="COD",
                max_length=20,
            ),
        ),
    ]
