# Generated by Django 6.0.3 on 2026-05-27 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_is_archived_order_idx_active_orders'),
        ('products', '0002_alter_product_name_alter_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.product'),
        ),
    ]
