# Generated by Django 6.0.3 on 2026-05-28 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_alter_orderitem_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("COD", "cash on delivery"), ("CARD", "card/online payment")],
                default="COD",
                max_length=20,
            ),
        ),
    ]
